{
 "title": "Chia",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Plots",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "total_plots", "legendFormat": "{{host}}" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(eligible_plots_total)\n", "legendFormat": "Plots Eligible" },
    { "expr": "sum(proofs_found_total)", "legendFormat": "Proofs Found" }
   ]
  },
  {
   "title": "Challenges",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "number_of_challenges_total" }
   ]
  },
  {
   "title": "Challenge Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "Average Check Duration"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(check_duration_bucket[5m])) by (le))",
     "legendFormat": "95th Percentile Check Duration"
    }
   ]
  }
 ]
}